import { useEffect, useState } from 'react'
import { motion, AnimatePresence, useScroll, useSpring } from 'framer-motion'
import { ArrowRight, CalendarCheck, Check, ChevronDown, Clock3, Globe2, Headphones, Share2, Mail, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Sparkles, Wrench, X, Zap, Droplets, Wind, Bug, PaintRoller, Hammer, PlugZap } from 'lucide-react'

const phone = '+971 56 477 7476'
const whatsapp = 'https://wa.me/971564777476'
const nav = [['Home','home'],['About','about'],['Services','services'],['Recent Work','work'],['Why Us','why-us'],['Contact','contact']]
const coreServices = [
  {name:'AC Services', icon:Wind, image:'/images/hero-technician.jpg', desc:'Keep every room comfortable with professional AC maintenance in Dubai.', items:['AC maintenance','AC deep cleaning','Soft AC cleaning','AC duct cleaning','Thermostat installation']},
  {name:'Plumbing', icon:Droplets, image:'/images/technician.jpg', desc:'Reliable plumbing services Dubai properties can count on.', items:['Leak and toilet repairs','Blockage removal','Water heaters','Faucets and showers','Custom plumbing work']},
  {name:'Electrical', icon:Zap, image:'/images/electrical.jpg', desc:'Careful electrical repairs and installations for safer properties.', items:['Electrical repairs','Wiring','Outlets and switches','Light fixtures','Custom electrical work']},
  {name:'Home Maintenance', icon:Wrench, image:'/images/dubai-marina.jpg', desc:'One dependable team for planned, preventive and everyday upkeep.', items:['Annual Maintenance Contracts','Basic AMC','Standard AMC','Executive AMC']},
]
const supporting = [
  {name:'Pest Control', icon:Bug, text:'Reliable residential and commercial pest control.'},
  {name:'Handyman Services', icon:Hammer, text:'TV installation, furniture assembly, tank cleaning, locks and repairs.'},
  {name:'Appliance Installation', icon:PlugZap, text:'Dishwashers, cookers, washing machines and AC units.'},
  {name:'Home Painting', icon:PaintRoller, text:'Professional interior and exterior property painting.'},
]
const projects = [
  {name:'Burj Khalifa, Sheikh Zayed Road', type:'Commercial', image:'/images/dubai-night.jpg'},
  {name:'Dubai Marina', type:'Residential', image:'/images/dubai-marina.jpg'},
  {name:'Palm Jumeirah, Dubai', type:'Commercial', image:'/images/technician.jpg'},
  {name:'Jumeirah Village Circle', type:'Residential & Commercial', image:'/images/electrical.jpg'},
]
const trust = ['Trained and knowledgeable technicians','Residential and commercial expertise','Responsive 24/7 assistance','Wide range of services','Coverage across Dubai','Careful and professional workmanship']
const steps = [
  ['Tell Us What You Need','Share the service, property location, and preferred time.'],
  ['Receive a Clear Assessment','Our team reviews the request and confirms the appropriate service.'],
  ['Technician Visit','A trained professional attends the property and completes the work carefully.'],
  ['Final Quality Check','The completed work is reviewed before the request is closed.'],
]
const areas = ['Deira','Dubai Marina','Palm Jumeirah','Jumeirah Village Circle','Downtown Dubai','Sheikh Zayed Road']
const reveal = {initial:{opacity:0,y:28}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.18}, transition:{duration:.65,ease:[.22,1,.36,1]}}

function ScrollProgress(){
  const {scrollYProgress}=useScroll()
  const scaleX=useSpring(scrollYProgress,{stiffness:120,damping:28,mass:.25})
  return <motion.div className="scroll-progress" style={{scaleX}} aria-hidden="true"/>
}

function Button({children, href='#quote', secondary=false, className=''}) { return <a href={href} className={`btn ${secondary?'btn-secondary':'btn-primary'} ${className}`}>{children}<ArrowRight size={17}/></a> }
function SectionHead({eyebrow, title, copy, light=false}) { return <motion.div {...reveal} className={`section-head ${light?'text-white':''}`}>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{copy&&<p className={light?'text-white/70':'text-ink/65'}>{copy}</p>}</motion.div> }
function Success({text}) { return <motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} className="success"><span><Check size={18}/></span>{text}</motion.div> }

function Header() {
  const [open,setOpen]=useState(false), [compact,setCompact]=useState(false)
  useEffect(()=>{ const f=()=>setCompact(scrollY>40); f(); addEventListener('scroll',f); return()=>removeEventListener('scroll',f)},[])
  useEffect(()=>{document.body.style.overflow=open?'hidden':''; return()=>{document.body.style.overflow=''}},[open])
  return <>
    <div className="utility"><div className="container flex items-center justify-between"><span className="hidden md:block">24/7 Maintenance Support Across Dubai</span><div className="flex items-center gap-5"><a href="tel:+971564777476"><Phone size={14}/><span>{phone}</span></a><a className="hidden md:flex" href="mailto:info@saveyourhome.ae"><Mail size={14}/>info@saveyourhome.ae</a><a href={whatsapp}><MessageCircle size={14}/>WhatsApp</a></div></div></div>
    <header className={`header ${compact?'compact':''}`}><div className="container nav-wrap"><a href="#home" aria-label="Save Your Home homepage"><img src="/images/logo.png" alt="Save Your Home Building Maintenance" className="logo"/></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([n,id])=><a key={id} href={`#${id}`}>{n}</a>)}<Button>Get a Free Quote</Button></nav><button className="menu-btn" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button></div></header>
    <AnimatePresence>{open&&<><motion.button aria-label="Close menu overlay" className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}/><motion.aside className="drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:28,stiffness:260}}><div className="flex items-center justify-between"><img src="/images/logo.png" className="w-40" alt="Save Your Home"/><button onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><nav>{nav.map(([n,id])=><a onClick={()=>setOpen(false)} key={id} href={`#${id}`}>{n}<ArrowRight size={17}/></a>)}</nav><Button className="mt-auto" href="#quote">Get a Free Quote</Button><a className="drawer-phone" href="tel:+971564777476"><Phone/> {phone}</a></motion.aside></>}</AnimatePresence>
  </>
}

function Hero(){return <section id="home" className="hero"><div className="container hero-grid"><motion.div initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.12}}}} className="hero-copy"><motion.p variants={{hidden:{opacity:0,y:16},show:{opacity:1,y:0}}} className="eyebrow">Trusted Building Maintenance in Dubai</motion.p><motion.h1 variants={{hidden:{opacity:0,y:22},show:{opacity:1,y:0}}}>Reliable Care for the Places That <em>Matter Most.</em></motion.h1><motion.p variants={{hidden:{opacity:0,y:22},show:{opacity:1,y:0}}} className="hero-lead">Professional residential and commercial maintenance services delivered by trained technicians across Dubai and the UAE.</motion.p><motion.div variants={{hidden:{opacity:0},show:{opacity:1}}} className="flex flex-wrap gap-3"><Button>Get a Free Quote</Button><Button href="#services" secondary>Explore Our Services</Button></motion.div><motion.div variants={{hidden:{opacity:0},show:{opacity:1}}} className="reassurance">{['24/7 Support','Trained Technicians','Residential & Commercial'].map(x=><span key={x}><Check size={14}/>{x}</span>)}</motion.div></motion.div><motion.div initial={{opacity:0,clipPath:'inset(12% 0 0 20%)'}} animate={{opacity:1,clipPath:'inset(0% 0 0 0%)'}} transition={{duration:1,ease:[.22,1,.36,1]}} className="hero-visual"><div className="hero-frame"></div><img src="/images/hero-maintenance.png" alt="Professional maintenance technician servicing a split AC unit in a modern Dubai property"/><div className="hero-card"><div className="icon-box"><ShieldCheck/></div><div><strong>Complete Property Care</strong><p>From urgent repairs to annual maintenance contracts.</p></div></div><div className="hero-tag">Dubai · UAE</div></motion.div></div></section>}

function QuickRequest(){const [sent,setSent]=useState(false);return <div id="quote" className="quick-wrap"><div className="container"><motion.form {...reveal} className="quick-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="quick-title"><span>Quick request</span><strong>What service do you need?</strong></div><label><span>Service</span><select aria-label="Select service" required defaultValue=""><option value="" disabled>Select a service</option>{[...coreServices,...supporting].map(s=><option key={s.name}>{s.name}</option>)}</select><ChevronDown/></label><label><span>Location</span><input required placeholder="e.g. Dubai Marina"/></label><label><span>Phone number</span><input required type="tel" placeholder="+971" pattern="[+0-9 ()-]{7,}"/></label><button className="btn btn-primary" type="submit">Request a Callback<ArrowRight size={17}/></button>{sent&&<div className="quick-success"><Check/> Request received — our team will call you shortly.</div>}</motion.form></div></div>}

function Introduction(){return <section id="about" className="section"><div className="container intro-grid"><motion.div {...reveal} className="intro-visual"><img src="/images/dubai-marina.jpg" alt="Well-maintained modern residential properties in Dubai Marina" loading="lazy"/><div className="trust-panel"><Headphones/><strong>Responsive support</strong><span>Residential & commercial</span></div></motion.div><div><SectionHead eyebrow="Dependable by design" title="Maintenance That Keeps Your Property at Its Best" copy="Save Your Home provides reliable maintenance solutions for residential and commercial properties across Dubai. Our trained team combines practical expertise, responsive service, and careful workmanship to keep every space safe, comfortable, and well maintained."/><div className="intro-list">{['Residential Maintenance','Commercial Maintenance','Preventive Maintenance','Emergency Support'].map((x,i)=><motion.div {...reveal} transition={{...reveal.transition,delay:i*.07}} key={x}><span>0{i+1}</span>{x}</motion.div>)}</div></div></div></section>}

function Services(){return <section id="services" className="section bg-cream"><div className="container"><SectionHead eyebrow="Complete Property Care" title="Everything Your Property Needs, Under One Roof" copy="One building maintenance company in Dubai for planned upkeep, urgent repairs and specialist care."/><div className="services-grid">{coreServices.map((s,i)=><motion.article {...reveal} key={s.name} className={`service-feature service-${i}`}><div className="service-image"><img src={s.image} alt={`${s.name} services for Dubai properties`} loading="lazy"/><div className="service-icon"><s.icon/></div></div><div className="service-body"><p className="service-num">0{i+1}</p><h3>{s.name}</h3><p>{s.desc}</p><ul>{s.items.map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="#quote">Request This Service<ArrowRight/></a></div></motion.article>)}</div><div className="support-services">{supporting.map(s=><motion.article {...reveal} key={s.name}><s.icon/><div><h3>{s.name}</h3><p>{s.text}</p><a href="#quote">Request service <ArrowRight/></a></div></motion.article>)}</div></div></section>}

function AMC(){return <section className="amc section"><div className="container"><div className="amc-top"><SectionHead eyebrow="Annual Maintenance Contracts" title="Year-Round Protection for Your Property" light copy="Choose an annual maintenance contract in Dubai shaped around your property's needs—without the uncertainty of reactive upkeep."/><Button href="#contact">Enquire About AMC Plans</Button></div><div className="amc-plans">{[['Basic AMC','Essential property maintenance'],['Standard AMC','Scheduled preventive visits'],['Executive AMC','Customised maintenance coverage']].map((p,i)=><motion.article {...reveal} key={p[0]}><span>0{i+1}</span><CalendarCheck/><h3>{p[0]}</h3><p>{p[1]}</p><a href="#contact">Discuss this plan <ArrowRight/></a></motion.article>)}</div><p className="amc-note">Contact our team to find the right maintenance plan for your property.</p></div></section>}

function Why(){return <section id="why-us" className="section"><div className="container why-grid"><motion.div {...reveal} className="why-image"><img src="/images/technician.jpg" alt="Professional maintenance technician carefully inspecting property systems" loading="lazy"/><div><Clock3/><strong>Available 24/7</strong></div></motion.div><div><SectionHead eyebrow="Why Save Your Home" title="Built Around Reliability, Not Just Repairs" copy="Every visit is approached with practical knowledge, respect for your property and clear communication."/><div className="reasons">{trust.map((x,i)=><motion.div {...reveal} key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></motion.div>)}</div></div></div></section>}

function Process(){return <section className="section process"><div className="container"><SectionHead eyebrow="A clear, considered process" title="From Request to Resolution"/><div className="timeline">{steps.map((s,i)=><motion.article {...reveal} key={s[0]}><div className="step-dot">{String(i+1).padStart(2,'0')}</div><h3>{s[0]}</h3><p>{s[1]}</p></motion.article>)}</div></div></section>}

function Work(){const [selected,setSelected]=useState(null);return <section id="work" className="section bg-cream"><div className="container"><div className="work-head"><SectionHead eyebrow="Our Work Across Dubai" title="Properties We’re Proud to Maintain"/><p>Residential and commercial environments supported with professional, thoughtful property care.</p></div><div className="project-grid">{projects.map((p,i)=><motion.button {...reveal} key={p.name} className={`project p-${i}`} onClick={()=>setSelected(p)}><img src={p.image} alt={`${p.name} maintenance project`} loading="lazy"/><span className="project-overlay"><small>{p.type}</small><strong>{p.name}</strong><i><ArrowRight/></i></span></motion.button>)}</div><Button href="#work" secondary className="mt-8">Explore Recent Work</Button></div><AnimatePresence>{selected&&<motion.div className="modal" role="dialog" aria-modal="true" aria-label={selected.name} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}><motion.div initial={{scale:.94,y:20}} animate={{scale:1,y:0}} exit={{scale:.96}} onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)} aria-label="Close project"><X/></button><img src={selected.image} alt={`${selected.name} project view`}/><div><p>{selected.type}</p><h3>{selected.name}</h3></div></motion.div></motion.div>}</AnimatePresence></section>}

function Areas(){return <section className="areas section"><div className="container areas-grid"><div><SectionHead eyebrow="Service Areas" title="Professional Maintenance Across Dubai" copy="Our team supports residential and commercial properties across key Dubai communities."/><Button href="#contact">Check Your Location</Button></div><motion.div {...reveal} className="map-visual"><div className="map-lines"></div>{areas.map((x,i)=><div className={`map-point mp-${i}`} key={x}><i></i><span>{x}</span></div>)}</motion.div></div></section>}

function BigCTA(){return <section className="section cta-section"><div className="container cta-grid"><motion.div {...reveal}><p className="eyebrow">Your dependable maintenance partner</p><h2>Your Property Deserves <em>Reliable Care.</em></h2><p>Whether it’s a quick repair, planned maintenance, or a complete annual maintenance contract, our team is ready to help.</p><div className="flex flex-wrap gap-3"><Button>Get a Free Quote</Button><a className="btn btn-secondary" href={whatsapp}><MessageCircle size={18}/>WhatsApp Us</a></div></motion.div><motion.div {...reveal} className="cta-image"><img src="/images/electrical.jpg" alt="Skilled technician carrying out professional property maintenance" loading="lazy"/><span><Sparkles/> Careful workmanship, every visit.</span></motion.div></div></section>}

function Contact(){const [status,setStatus]=useState('idle'),[errors,setErrors]=useState({}); const submit=e=>{e.preventDefault();const d=new FormData(e.currentTarget), er={};['name','phone','email','service','location'].forEach(k=>{if(!d.get(k)?.trim())er[k]='This field is required'});if(d.get('email')&&!/^\S+@\S+\.\S+$/.test(d.get('email')))er.email='Enter a valid email';setErrors(er);if(Object.keys(er).length)return;setStatus('loading');setTimeout(()=>setStatus('success'),900)};return <section id="contact" className="section contact"><div className="container contact-grid"><div><SectionHead eyebrow="Contact our team" title="Let’s Take Care of Your Property" copy="Tell us what you need and our responsive team will help arrange the appropriate service."/><div className="contact-details"><div><MapPin/><p><strong>Main Office</strong><span>Tanvi Building, Airport Road<br/>Office No. 9, Deira, Port Saeed, Dubai</span></p></div><div><Phone/><p><strong>Phone</strong><a href="tel:+971564777476">{phone}</a></p></div><div><Mail/><p><strong>Email</strong><a href="mailto:info@saveyourhome.ae">info@saveyourhome.ae</a></p></div><div><Clock3/><p><strong>Availability</strong><span>24/7</span></p></div></div></div><motion.form {...reveal} className="contact-form" onSubmit={submit} noValidate>{status==='success'?<Success text="Thank you. Your request has been sent and our team will be in touch shortly."/>:<><div className="form-title"><span>Free quote request</span><h3>How can we help?</h3></div><div className="form-grid">{[['name','Full name','text','Your name'],['phone','Phone number','tel','+971'],['email','Email address','email','you@example.com'],['location','Property location','text','Area in Dubai']].map(f=><label key={f[0]}><span>{f[1]}</span><input name={f[0]} type={f[2]} placeholder={f[3]} aria-invalid={!!errors[f[0]]}/>{errors[f[0]]&&<small>{errors[f[0]]}</small>}</label>)}<label className="full"><span>Required service</span><select name="service" defaultValue="" aria-invalid={!!errors.service}><option value="" disabled>Select a service</option>{[...coreServices,...supporting].map(s=><option key={s.name}>{s.name}</option>)}</select>{errors.service&&<small>{errors.service}</small>}</label><label className="full"><span>Message <i>(optional)</i></span><textarea name="message" rows="4" placeholder="Tell us a little about the maintenance you need"/></label></div><button className="btn btn-primary w-full justify-center" disabled={status==='loading'}>{status==='loading'?'Sending request…':<>Submit Request<ArrowRight size={17}/></>}</button></>}</motion.form></div></section>}

function Footer(){return <footer><div className="container footer-grid"><div><img src="/images/logo.png" alt="Save Your Home Building Maintenance"/><p>Reliable residential and commercial maintenance services delivered across Dubai with professionalism, care, and responsive support.</p><div className="socials"><a href="https://www.facebook.com/" aria-label="Facebook"><Globe2/></a><a href="https://www.instagram.com/" aria-label="Instagram"><Share2/></a><a href={whatsapp} aria-label="WhatsApp"><MessageCircle/></a></div></div><div><h3>Navigate</h3>{nav.map(([n,id])=><a href={`#${id}`} key={id}>{n}</a>)}</div><div><h3>Services</h3>{['Home Maintenance','AC Services','Plumbing','Electrical','Handyman','Home Painting'].map(x=><a href="#services" key={x}>{x}</a>)}</div><div><h3>Contact</h3><a href="tel:+971564777476">{phone}</a><a href="mailto:info@saveyourhome.ae">info@saveyourhome.ae</a><p>Tanvi Building, Airport Road<br/>Deira, Dubai</p></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Save Your Home. All rights reserved.</span><a href="#">Privacy</a></div></footer>}

export default function App(){return <><ScrollProgress/><Header/><main><Hero/><QuickRequest/><Introduction/><Services/><AMC/><Why/><Process/><Work/><Areas/><BigCTA/><Contact/></main><Footer/><div className="floating-actions"><a href={whatsapp} aria-label="WhatsApp Save Your Home"><MessageCircle/><span>WhatsApp</span></a><a href="tel:+971564777476" aria-label="Call Save Your Home"><Phone/><span>Call now</span></a></div></>}
